#!/bin/sh

# Starts the ucarp process when the virtual ip interface is started.  Note that the process
# is killed automatically when the interface goes down.
#
# The script uses the following params from the environment.  The ubuntu if-up/if-down commands
# add these (among other things) to the enviroment from interfaces file.
#
# IFACE - interface name such as eth0
# IF_ADDRESS - The real ip address of the interface

if [ '{{ vip.interface }}' = {{ vip.interface }} ]; then
  kill  $(ps -ef | grep "ucarp -i '{{ vip.interface }}'" | awk '{print $2}')
  ucarp -i '{{ vip.interface }}' -p {{ vip.ucarp_password }} -v {{ vip.ucarp_id }} -B -n -a {{ vip.ip_address }} -s '{{ inventory_hostname }}' -u {{ vip.up_script }} -d {{ vip.down_script }} -x {{ vip.cidr_prefix }}
fi
